### PR TITLE
Support overriding toString method of a node from NodeSpec

### PR DESCRIPTION
**Pull request by d4rkr00t**
Closes: https://github.com/ProseMirror/prosemirror/issues/810

I've added a few tests for this change, but also quite a few other tests are failing even in master. Haven't looked at why :)

### CODE REVIEW

**Comment by marijnh** [comment]
> I've added a few tests for this change, but also quite a few other tests are failing even in master. Haven't looked at why :)

Master passes fine for me (and for travis). So I suspect the problem is that you broke them. Every object has a `toString` property, via `Object.prototype.toString`, so you'll have to either check for a direct property, or use a different name for the spec property (which would be a good idea, since `toString` already has a meaning, and this'll cause weird crashes when you try to convert the spec to a string, since the method will be called without argument but expects one).

**Comment by d4rkr00t** [comment]
Yeah, it totally make sense. I renamed `toString` -> `toDebugString`. Open to a better name suggestions.

Still, tests for DOMParser are failing for me on clean master without **any** changes. 

screen shot 2018-06-22 at 10 59 53 am

I tried node 6 and 8, npm 6 and 5, and yarn 1.3.2 to install dependencies, still failing.

**Comment by marijnh** [comment]
Nice. Merged as 2f40546.

I still can't reproduce the failing tests, going to try a reinstall of the module.

**Comment by marijnh** [comment]
The problem is that when you install prosemirror-model on its own, it installs itself as one of its dependencies (via a test helper package), and then when running the tests, it'll load two instances of prosemirror-model causing instanceof tests to fail.

Not sure how to wrangle npm to work around this yet.

**Comment by marijnh** [comment]
I've kludged around the test issue in patch 1950a1a

**Comment by d4rkr00t** [comment]
Nice!

**Pull request closed without merging**
