### PR TITLE
Fix missing mark when parsing nested mark with same type

### PR DESCRIPTION
**Pull request by lastnigtic**
Fix issue [https://github.com/ProseMirror/prosemirror/issues/1093](https://github.com/ProseMirror/prosemirror/issues/1093)

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks. Could you add a test (in test/test-dom.js) that ensures this stays fixed?

**Comment by lastnigtic** [comment]
I just found that I had missing some cases.
Should I create another pull request or just push another commit?

**Comment by marijnh** [comment]
Adding commits (or even force-pushing over the original ones) is fine.

**Comment by lastnigtic** [comment]
I have pushed my code. Do you have any suggestions for improvement on these changes?

**Comment by marijnh** [comment]
Thanks! Merged.

**Pull request merged**
